# Generated by Django 2.2.1 on 2019-05-28 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APLICACAO', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='peso',
            new_name='peso1',
        ),
    ]
