# Generated by Django 2.2.1 on 2019-05-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APLICACAO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='ataque_especial',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='defesa_especial',
            field=models.CharField(max_length=50),
        ),
    ]
