# Generated by Django 2.2.1 on 2019-05-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APLICACAO', '0002_auto_20190516_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='experiencia',
            field=models.PositiveIntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
