# Generated by Django 2.2.1 on 2019-05-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APLICACAO', '0003_auto_20190528_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='peso',
            field=models.FloatField(),
        ),
    ]
