# Generated by Django 2.2.1 on 2019-05-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APLICACAO', '0003_pokemon_experiencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='ataque_especial',
            new_name='habilidades',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='defesa_especial',
            new_name='movimentos',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='experiencia',
            field=models.PositiveIntegerField(),
        ),
    ]
