# Generated by Django 2.2.1 on 2019-05-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APLICACAO', '0004_auto_20190528_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='imagem1',
            field=models.FileField(default=0, upload_to='fotos/'),
            preserve_default=False,
        ),
    ]
